name: CI

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]
    workflow_dispatch:
      inputs: {}

jobs:
    ci:
        runs-on: ubuntu-latest
        name: Build and test
        steps:
            -  uses: actions/checkout@v3
            - uses: pnpm/action-setup@v4
              with:
                version: 9
            -  name: Use Node 20
               uses: actions/setup-node@v4
               with:
                node-version: '20.x'
                cache: pnpm
            -  run: pnpm install
            -  run: npx puppeteer browsers install chrome
               name: Install chrome for puppeteer
            -  run: pnpm build
            -  run: pnpm check-types
            -  run: pnpm test